salary_calculator/urls.py
# -*- coding: utf-8 -*-

#=============================================
#
# Copyright 2012 David Racca and Matias Molina.
#
# This file is part of ADIUC Salary Calculator.
#
# ADIUC Salary Calculator is free software: you can redistribute it and/or 
# modify it under the terms of the GNU General Public License as published 
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ADIUC Salary Calculator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ADIUC Salary Calculator.  If not, see 
# <http://www.gnu.org/licenses/>.
#
#=============================================

from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^calculate/$', 'salary_calculator_app.views.calculate', name='calculate salary'),
    # url(r'^salary_calculator/', include('salary_calculator.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

salary_calculator_app/models.py
# -*- coding: utf-8 -*-

#=============================================
#
# Copyright 2012 David Racca and Matias Molina.
#
# This file is part of ADIUC Salary Calculator.
#
# ADIUC Salary Calculator is free software: you can redistribute it and/or 
# modify it under the terms of the GNU General Public License as published 
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ADIUC Salary Calculator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ADIUC Salary Calculator.  If not, see 
# <http://www.gnu.org/licenses/>.
#
#=============================================

from django.db import models

from salary_calculator_app.validators import *


class GarantiaSalarialPreUniversitaria(models.Model):
    """ garantía salarial para cargos preuniversitarios """
    
    cargo = models.ForeignKey('CargoPreUniversitario',
        help_text=u'El cargo docente sobre el que se aplica esta garantía.')
    
    valor = models.FloatField(u'Monto minimo', validators=[validate_isgezero],
        help_text=u'Monto mínimo, igualado éste no se aplica la garantía.')

    vigencia_desde = models.DateField(u'Vigente desde',
        help_text=u'Fecha a partir de la cual esta garantía comienza a tener vigencia.')

    vigencia_hasta = models.DateField(u'Vigente hasta',
        help_text=u'Fecha a partir de la cual esta garantía deja de ser vigente.')


class GarantiaSalarialUniversitaria(models.Model):
    """Representa el valor minimo que un Cargo puede cobrar."""

    cargo = models.ForeignKey('CargoUniversitario',
        help_text=u'El cargo docente sobre el que se aplica esta garantía.')

    valor_minimo = models.FloatField(u'Monto minimo', validators=[validate_isgezero],
        help_text=u'Monto mínimo, igualado éste no se aplica la garantía.')

    valor_st = models.FloatField(u'Monto de la garantía', validators=[validate_isgezero],
        help_text=u'El monto de esta garantía sin título adicional.')
    valor_doctorado = models.FloatField(u'Monto de la garantía', validators=[validate_isgezero],
        help_text=u'El monto de esta garantía con título de doctorado.')
    valor_master = models.FloatField(u'Monto de la garantía', validators=[validate_isgezero],
        help_text=u'El monto de esta garantía con título de master.')
    
    antiguedad_min = models.IntegerField(u'Antiguedad mínima',
        help_text=u'A partir de esta antiguedad corresponde el monto asociado a la garantía.' )
    
    antiguedad_max = models.IntegerField(u'Antiguedad máxima',
        help_text=u'Hasta esta antiguedad (inclusive) corresponde el monto asociado a la garantía.' )
    
    vigencia_desde = models.DateField(u'Vigente desde',
        help_text=u'Fecha a partir de la cual esta garantía comienza a tener vigencia.')

    vigencia_hasta = models.DateField(u'Vigente hasta',
        help_text=u'Fecha a partir de la cual esta garantía deja de ser vigente.')    

    class Meta:
        ordering = ['cargo', 'valor_minimo']

    def __unicode__(self):
        return unicode(self.cargo) + " $" + unicode(self.valor) + " [" + unicode(self.vigencia_desde) + " / " + unicode(self.vigencia_hasta) + "]"


class Cargo(models.Model):
    """Modelo que representa un Cargo, ya sea pre o universitario."""

    lu = models.PositiveSmallIntegerField(u'Código LU', validators=[validate_isgzero],
        help_text=u'El código L.U. del cargo que figura en la planilla de la UNC.')
    pampa = models.PositiveSmallIntegerField(u'Código PAMPA', unique=True, validators=[validate_isgzero],
        help_text=u'El código PAMPA del cargo que figura en la planilla de la UNC.')
    denominacion = models.ForeignKey('DenominacionCargo',
        help_text=u'El nombre del cargo asociado.')

    #rem_fijas = models.ManyToManyField('RemuneracionFija', blank=True)
    #rem_porcentuales = models.ManyToManyField('RemuneracionPorcentual', blank=True)
    #ret_fijas = models.ManyToManyField('RetencionFija', blank=True)
    #ret_porcentuales = models.ManyToManyField('RetencionPorcentual', blank=True)

    class Meta:
        ordering = ['denominacion']

    def __unicode__(self):
        return unicode(self.denominacion)


class DenominacionCargo(models.Model):
    """El nombre de un cargo docente. Ej: Profesor Adjunto, Ayudante Alumno, etc"""

    nombre = models.CharField(u'Denominacion del Cargo', max_length=50, unique=True,
        help_text=u'El nombre de un cargo docente. Ej: Profesor Titular, Profesor Asociado, etc')
    
    class Meta:
        ordering = ['nombre']

    def __unicode__(self):
        return self.nombre


class CargoUniversitario(Cargo):
    """Cargo de docente Universitario."""

    DEDICACION_OPCS = (
        ('D.E', u'Dedicación Exclusiva'),
        ('D.S.E', u'Dedicación Semi Exclusiva'),
        ('D.S', u'Dedicación Simple')
    )
    dedicacion = models.CharField(u'Dedicación', max_length=5, choices=DEDICACION_OPCS,
        help_text=u'El tipo de dedicación para el cargo. Pueden ser dedicación exclusiva, semi-exclusiva o simple.')
    #adic2003 = models.FloatField(u'Adic. 8% RHCS 153/03', blank=True, null=True,    
    #help_text=u'Es el adicional del 8% del salario básico del año 2003 que le corresponde a este cargo.')

    class Meta:
        ordering = ['pampa']

    def __unicode__(self):
        return super(CargoUniversitario, self).__unicode__() + " - " + self.dedicacion


class CargoPreUniversitario(Cargo):
    """Cargo de docente Preuniversitario."""

    TIPOHORAS_OPCS = (
        ('C', u'Cátedra'),
        ('R', u'Relog')
    )
    horas = models.FloatField(u'Cantidad de Horas Cátedra', validators=[validate_isgezero],
        help_text=u'La cantidad de horas para el cargo como figuran en la planilla de la UNC. Ej: Al cargo "Vice Director de 1°" le corresponden 25 horas.')
    tipo_horas = models.CharField(u'Tipo de Horas', max_length=1, choices=TIPOHORAS_OPCS,
        help_text=u'El tipo de horas del cargo.')
    pago_por_hora=models.BooleanField(u'Pago por hora?',
        help_text=u'Poner "Sí" si este cargo se paga por cantidad de horas. Poner "No" en caso contrario.')

    class Meta:
        ordering = ['lu']

    def __unicode__(self):
        if self.pago_por_hora or self.horas <= 0.:
            return super(CargoPreUniversitario, self).__unicode__()
        return super(CargoPreUniversitario, self).__unicode__() + " - " + unicode(self.horas) + "hs"


class Retencion(models.Model):
    """Representa a una retencion."""

    MODO_OPCS = (
        ('P', u'Se aplica a la persona (solo una vez).'),
        ('C', u'Se aplica por cargo (una vez por cada cargo).'),
    )

    # Tuplas de opciones.
    APP_OPCS = (
        ('U', u'Cargos Universitarios'),
        ('P', u'Cargos Preuniversitarios'),
        ('T', u'Todos los cargos')
    )

    codigo = models.CharField(u'Código', max_length=5,
        help_text=u'El código de la retencion tal cual figura en la lista de la web de ADIUC.')
    nombre  = models.CharField(u'Nombre', max_length=50,
        help_text=u'El nombre de la retencion tal cual figura en la lista de la web de ADIUC.')
    aplicacion = models.CharField(u'Aplica a', max_length=1, choices=APP_OPCS,
        help_text=u'A qué tipo de cargo aplica esta retencion.')
    modo = models.CharField(u'Modo', max_length=1,choices=MODO_OPCS)

    class Meta:
        ordering = ['codigo', 'nombre', 'aplicacion']

    def __unicode__(self):
        return self.codigo + u" " + self.nombre


# Algunos conceptos importantes:
# Remuneracion REMUNERATIVA: se denomina así a todo aquel ítem del 
# salario que tiene DESCUENTOS DE LEY (Jubilación, Obra social, ART).
# Remuneracion BONIFICABLE: se denominan así a todos los ítems del salario al que se le aplican los
# porcentuales de ANTIGÜEDAD de la escala de Art. Nº de la Ley Nº 1820.
class Remuneracion(models.Model):
    """Representa un adicional, es decir, una remuneracion."""

    MODO_OPCS = (
        ('P', u'Se aplica a la persona (solo una vez).'),
        ('C', u'Se aplica por cargo (una vez por cada cargo).'),
    )

    # Tuplas de opciones.
    APP_OPCS = (
        ('U', u'Cargos Universitarios'),
        ('P', u'Cargos Preuniversitarios'),
        ('T', u'Todos los cargos')
    )

    codigo = models.CharField(u'Código', max_length=5,
        help_text=u'El código de la remuneracion tal cual figura en la lista de la web de ADIUC.')
    nombre  = models.CharField(u'Nombre', max_length=50,
        help_text=u'El nombre de la remuneracion tal cual figura en la lista de la web de ADIUC.')
    aplicacion = models.CharField(u'Aplica a', max_length=1, choices=APP_OPCS,
        help_text=u'A qué tipo de cargo aplica esta remuneracion.')
    modo = models.CharField(u'Modo', max_length=1,choices=MODO_OPCS)
    remunerativo = models.BooleanField(u'Remunerativa',
        help_text=u'Una remuneración es remunerativa cuando se le aplican descuentos de Ley (jubilación, obra social, art, etc.)')
    bonificable = models.BooleanField(u'Bonificable',
        help_text=u'Una remuneración es bonificable cuando se le aplican los porcentuales de Antiguedad.')

    class Meta:
        ordering = ['codigo', 'nombre', 'aplicacion']

    def __unicode__(self):
        result = self.codigo + u" " + self.nombre
        if self.remunerativo:
            result  += u' R'
        else:
            result +=  u' NR'
        if self.bonificable:
            result += u'B'
        else:
            result += u'NB'
        return result


class RetencionPorcentual(models.Model):
    """Una retencion que especifica el porcentaje del descuento que debe realizarse."""

    retencion = models.ForeignKey('Retencion',
        help_text = u'La retención relacionada con esta retención porcentual.')

salary_calculator_app/forms.py
# -*- coding: utf-8 -*-

#=============================================
#
# Copyright 2012 David Racca and Matias Molina.
#
# This file is part of ADIUC Salary Calculator.
#
# ADIUC Salary Calculator is free software: you can redistribute it and/or 
# modify it under the terms of the GNU General Public License as published 
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ADIUC Salary Calculator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ADIUC Salary Calculator.  If not, see 
# <http://www.gnu.org/licenses/>.
#
#=============================================

from django import forms
from models import *
import datetime


#Utilizada para filtrar datos en AFamiliaresForm (asignaciones familiares)
def get_concepts_asigf():
    asignaciones = AsignacionFamiliar.objects.all()
    result = list()
    for a in asignaciones:
        c = a.concepto
        result.append(c)
    return list(set(result))


class DetailsForm(forms.Form):
    """Formulario con opciones extras."""

    sis = forms.BooleanField(label=u'Servicio Integral de  Sepelio (SIS)', required=False)
    subsidio_fallecimiento  = forms.BooleanField(label=u'Subsidio por Fallecimiento', required=False)
    fondo_solidario_mayores = forms.IntegerField(label=u'Mayores de 55 años.',
        widget=forms.Select(choices=[(i, i) for i in range(16)]))
    fondo_solidario_menores = forms.IntegerField(label=u'Menores de 55 años.',
        widget=forms.Select(choices=[(i, i) for i in range(16)]))


class AFamiliaresForm(forms.Form):
    """Formulario con opciones específicas opcionales."""

    asig_familiar = forms.ChoiceField(
        label=u'Asignación',
        required=False,
        choices=[(i, unicode(i)) for i in get_concepts_asigf()],
        help_text= u'Seleccione el tipo de asignación.'
    )


class AFamiliaresFormEspecial(forms.Form):
    """Form para ingresar los datos de las asig familiares. Tiene un select
    para ingresar la cantidad de hijos."""

    cant_hijos = forms.IntegerField(
        label=u'Cantidad de Hijos',
        required=False,
        widget=forms.Select(choices=[(i, i) for i in range(16)]),
        help_text=u'Seleccione el tipo de asignación'
    )


class ImpuestoGananciasForm(forms.Form):
    """Formulario para que el usuario ingrese datos referidos al calculo del impuesto a las ganancias"""

    estado_civil = forms.ChoiceField(
        label=u'Estado Civil',
        choices=[(1, u'Soltero/a'), (2, u'Casado/a'), (3, u'Divorciado/a'), (4, u'Viudo/a')]
    )
    conyuge = forms.ChoiceField(
        label=u'En caso de ser casado, ¿El salario neto de su cónyuge supera los $12960 anuales?',
        choices=[(2, 'No'), (1, u'Sí')]
    )
    nro_hijos_menores_24 = forms.ChoiceField(
        label=u'N° de hijos/hijastros menores de 24 años o incapacitados para el trabajo',
        choices=[(i, i) for i in range(15)]
    )
    nro_descendientes = forms.ChoiceField(
       label=u'N° de nietos/bisnietos menores de 24 años o incapacitados para el trabajo',
        choices=[(i, i) for i in range(15)]
    )
    nro_ascendientes = forms.ChoiceField(
       label=u'N° de padres, padrastros y abuelos incapacitados para el trabajo',
        choices=[(i, i) for i in range(6)]
    )
    nro_suegros_yernos_nueras = forms.ChoiceField(
        label=u'N° de suegro/a, yernos/nueras menores de 24 años o incapacitados para el trabajo',
        choices=[(i, i) for i in range(6)]
    )


class CommonForm(forms.Form):
    """Formulario para el cálculo de salario docente. Contiene todos los valores
    que dependen de la persona y no de cada cargo por separado."""

    fecha = forms.DateField(
        label=u'Periodo a calcular',
        initial=datetime.date.today,
        help_text=u'Seleccione una fecha para hacer el cálculo del salario.'
    )

    antiguedad = forms.ChoiceField(
        label=u'Antigüedad', 
        choices=[(i, unicode(i)) for i in 
            range(0, max(AntiguedadUniversitaria.objects.all()[AntiguedadUniversitaria.objects.count()-1].anio,
            AntiguedadPreUniversitaria.objects.all()[AntiguedadPreUniversitaria.objects.count()-1].anio)+1)
        ],
        #choices=[(i, unicode(i)) for i in range(0, 24)],
        help_text=u'Ingrese su antigüedad docente'
    )

    master = forms.BooleanField(label=u'Añadir Título de Maestría', required=False)
    doctorado = forms.BooleanField(label=u'Añadir Título de Doctorado', required=False)

    afiliado = forms.BooleanField(label=u'Afiliado a ADIUC', required=False)
    daspu = forms.BooleanField(label=u'Considerar servicios DASPU', required=False)
    ganancias = forms.BooleanField(label=u'Considerar Impuesto a las Ganancias', required=False)


class CargoUnivForm(forms.Form):
    """Formulario de calculo de salario docente para docentes universitarios."""

    cargo = forms.ModelChoiceField(
        label=u'Cargo',
        queryset=CargoUniversitario.objects.all(),
        empty_label=None,
        help_text=u'Ingrese el nombre del cargo.'
    )


class CargoPreUnivForm(forms.Form):
    """Formulario de calculo de salario docente para docentes Pre-universitarios."""

    cargo = forms.ModelChoiceField(label=u'Cargo', queryset=CargoPreUniversitario.objects.all(), empty_label=None,
       widget=forms.Select(attrs={'onChange': 'show_horas(this)', 'onLoad':'show_horas(this)', 'onKeyUp':'this.blur();this.focus();'}),
       help_text=u'Ingrese el nombre del cargo.'
    )

    horas = forms.FloatField(label=u'Horas de trabajo', min_value=0., max_value=99., initial=1., required=True,
        widget=forms.TextInput(attrs={'maxlength':'5', 'style':'width: 50px;'}),
        help_text=u'Ingrese la cantidad de horas asociadas al cargo.'
    )

    pago_por_horas_info = forms.ChoiceField(
        required=False, 
        choices=[(unicode(c.id), unicode(c.pago_por_hora))  for c in CargoPreUniversitario.objects.all()],
        widget=forms.Select(attrs={'style':'display: none;'})
    )

salary_calculator_app/templates/salary_calculated.html
<!--=============================================
#
# Copyright 2012 David Racca and Matias Molina.
#
# This file is part of ADIUC Salary Calculator.
#
# ADIUC Salary Calculator is free software: you can redistribute it and/or 
# modify it under the terms of the GNU General Public License as published 
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ADIUC Salary Calculator is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ADIUC Salary Calculator.  If not, see 
# <http://www.gnu.org/licenses/>.
#
==============================================-->

{% load static %}

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es-es" lang="es-es" dir="ltr">

	<head>
		<title>C&aacute;lculo Salarial</title>
    	<link rel="stylesheet" href="{% get_static_prefix %}css/style.css" type="text/css" />
	</head>

	<body>
	<div align=center>
	{% if error_msg %}
	    <div class="errorbox">{{ error_msg }}</div>
	{% else %}
			<div class = "title">
			    C&aacute;lculo salarial para el periodo: {{ fecha.month }} / {{ fecha.year }}
			</div>

            <br>
            
            <div class="results_cargo">
                {% if afamiliar_list or rem_fijas_persona or rem_porc_persona or ret_fijas_persona or ret_porc_persona %}
                <table class="result" cellspaing=2><br>
    
                    <div class="title_importes"><b>Importes por Persona:</b></div>
                    <tr>
                        <th> C&oacute;digo </th>
                        <th> Detalle </th>
                        <th> Importe (+) </th>
                        <th> Importe (-) </th>
                    </tr>

                    {% for afamiliar in afamiliares_list %}
                        <tr>
                        <td>  </td>
                        <td> Asignaci&oacute;n Familiar ({{ afamiliar.concepto }})</td>
                        <td class="adicionales"> {{ afamiliar.valor|floatformat:-2 }} </td>
                        <td></td>
                        </tr>
                    {% endfor %}
                    
                    {% for rem,importe in rem_fijas_persona %}
                        <tr>
                        <td> {{ rem.remuneracion.codigo }} </td>
                        <td> {{ rem.remuneracion.nombre }} </td>
                        <td class="adicionales"> {{ importe|floatformat:-2 }} </td>
                        <td></td>
                        </tr>
                    {% endfor %}
                    
                    {% for rem,importe in rem_porc_persona %}
                        <tr>
                        <td> {{ rem.remuneracion.codigo }} </td>
                        <td> {{ rem.remuneracion.nombre }} ({{ rem.porcentaje }}%) </td>
                        <td class="adicionales"> {{ importe|floatformat:-2 }} </td>
                        <td></td>
                        </tr>
                    {% endfor %}

                    {% for ret,importe in ret_fijas_persona %}
                        <tr>
                        {% if ret.retencion.codigo == '42/0' %}
                            <td class="estimativo"> {{ ret.retencion.codigo }} </td>
                            <td class="estimativo"> {{ ret.retencion.nombre }}<sup>(1)</sup> </td>
                        {% else %}
                            <td> {{ ret.retencion.codigo }} </td>
                            <td> {{ ret.retencion.nombre }} </td>
                        {% endif %}
                        <td>  </td>
                        <td class="descuentos"> {% if importe > 0 %}-{% endif %}{{ importe|floatformat:-2 }} </td>
                        </tr>
                    {% endfor %}
                    
                    {% for ret,importe in ret_porc_persona %}
                        <tr>
                        <td> {{ ret.retencion.codigo }} </td>
                        <td> {{ ret.retencion.nombre }} ({{ ret.porcentaje }}%) </td>
                        <td></td>
                        <td class="descuentos"> {% if importe > 0 %}-{% endif %}{{ importe|floatformat:-2 }} </td>
                        </tr>
                    {% endfor %}
                    
                    
                </table>
                {% endif %}
               <hr>     

                <div class="title_importes"><b>Cargos:</b></div>
                {% for res in lista_res %}
                <table>
                    <tr>
                        <td> Cargo: </td>
                        <td>{{ res.cargo.denominacion }} {% if res.cargo.dedicacion %}, {{ res.cargo.get_dedicacion_display }}{% endif %}</td>
                    </tr>
                    <tr> <td> C&oacute;digo LU: </td> <td> {{ res.cargo.lu }} </td> </tr>
                    <tr> <td> C&oacute;digo PAMPA: </td> <td> {{ res.cargo.pampa }} </td> </tr>
                </table>
                <table class="result" cellspaing=2><br>
                    <tr>
                        <th> C&oacute;digo </th>
                        <th> Detalle </th>
                        <th> Importe (+) </th>
                        <th> Importe (-) </th>
                    </tr>
                    <tr>
                        <td> 10 </td>
                        <td> Sueldo B&aacute;sico </td>
                        <td> {% if res.cargo.pago_por_hora %} {{ res.basico_horas|floatformat:-2 }} {% else %} {{ res.basico|floatformat:-2 }} {% endif %} </td>
                        <td></td>
                    </tr>

                    <tr>
                        <td>{{ res.antiguedad.remuneracion.codigo }}</td>
                        <td> {{ res.antiguedad.remuneracion.nombre }} ({{res.antiguedad.anio}} años - {{ res.antiguedad.porcentaje }}%)</td>
                        <td>{{ res.antiguedad_importe|floatformat:-2 }} </td>
                        <td></td>
                    </tr>

                    <tr class="bold">
                        <td></td>
                        <td>Salario Bruto:</td>
                        <td>{{ res.salario_bruto|floatformat:-2 }} </td>
                        <td></td>
                    </tr>

                    {% for obj, importe in res.remuneraciones %}
						<tr>
                            <td> {{ obj.remuneracion.codigo }} </td>
                            <td> {{ obj.remuneracion.nombre }} {% if obj.porcentaje %}({{ obj.porcentaje }}%){% endif %} </td>
                            <td class="adicionales">{{ importe|floatformat:-2 }} </td>
                            <td></td>
                        </tr>
                    {% endfor %}

                    {% for obj, importe in res.retenciones %}
                     <tr>
                        <td> {{ obj.retencion.codigo }} </td>
                        <td> {{ obj.retencion.nombre }} {% if obj.porcentaje %}(-{{ obj.porcentaje }}%){% endif %} </td>
                        <td></td>
                        <td class="descuentos">{% if importe > 0 %}-{% endif %}{{ importe|floatformat:-2 }}</td>
                    </tr>
                    {% endfor %}
                    
                    {% if res.daspu %}
                    <tr>
                        <td> {{ res.daspu.retencion.retencion.codigo }} </td>
                        <td> {{ res.daspu.retencion.retencion.nombre }}
                            ({{res.daspu.retencion.porcentaje}}% 
                            {% if res.daspu_extra %} + {{ res.daspu_extra|floatformat:-2 }} extra por m&iacute;nimo {% endif %})
                        </td>
                        <td>  </td>
                        <td class="descuentos"> {% if res.daspu_importe > 0 %}-{% endif %}{{ res.daspu_importe|floatformat:-2 }} </td>
                    </tr>
                    {% endif %}

                    <tr class="bold">
                        <td></td>
                        <td> Adicionales: </td>
                        <td class="adicionales"> {{ res.acum_rem|floatformat:-2 }} </td>
                        <td></td>
                    </tr>
                    <tr class="bold">
                        <td></td>
                        <td> Descuentos: </td>
                        <td></td>
                        <td class="descuentos"> {% if res.acum_ret > 0 %}-{% endif %}{{ res.acum_ret|floatformat:-2 }} </td>
                    </tr>
                    <tr class="bold">
                        <td></td>
                        <td> Salario Neto: </td>
                        <td> {{ res.salario_neto|floatformat:-2 }} </td>
                        <td></td>
                    </tr>
                </table>
                {% endfor %}

            </div>

            <div class="totales bold">
                <table id="table_totales">
                    <tr>
                        <td> Total Bruto: </td>
                        <td > {{ total_bruto|floatformat:-2 }} </td>
                    </tr>
                    <tr>
                        <td> Total Adicionales: </td>
                        <td> <font color="#00bb00"> {{ total_rem|floatformat:-2 }} </td>
                    </tr>
                    <tr>
                        <td> Total Descuentos: </td>
                        <td> <font color="#660000"> {% if total_ret > 0 %}-{% endif %}{{ total_ret|floatformat:-2 }} </fonts></td>
                    </tr>
                    <tr>
                        <td> Total Neto: </td>
                        <td> {{ total_neto|floatformat:-2 }} </td>
                    </tr>
                </table>
            </div>

            <div class="referencias">
                <sup>(1)</sup> C&aacute;lculo estimativo.
            </div>

            <br><br>        
	{% endif %} <!-- error_msg -->
        <a class="agregar_quitar"href="javascript: history.go(-1)"> Volver</a>

	</div>

	</body>

</html>